### PR TITLE
Kaiwen Wang

### PR DESCRIPTION
**Pull request by kevinmaxwang**
@yihuiwang96
Hi My name is Kevin. What's your name and your favorite color?

### CODE REVIEW

**Comment by kevinmaxwang** [comment]
@yihuiwang96

**Comment by kevinmaxwang** [comment]
@ShangqingLi

**Comment by ShangqingLi** [comment]
what's your name

**Comment by kevinmaxwang** [comment]
@ShangqingLi 
My name is Kaiwen. You can call me Kevin.

**Pull request closed without merging**
